export const introSequence = (): Array<string | number> => {
  return [
    1000,
    'Elysium.SatelliteSystem Booting Up',
    100,
    'Elysium.SatelliteSystem Booting Up.',
    100,
    'Elysium.SatelliteSystem Booting Up..',
    100,
    'Elysium.SatelliteSystem Booting Up...',
    100,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize..',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize...',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize....',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize.....',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......\nE',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......\nE\nE',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......\nE\nE\nE',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......\nE\nE\nE\nE',
    50,
    'Elysium.SatelliteSystem Booting Up...\nnew Data.Repository [NEW USER]\n[User Name].Elysium.Chip.DeathProtocol Initialize......\nE\nE\nE\nE\nE',
  ];
};
